export const SEARCH_WORD = 'SEARCH_WORD';
export const CLEAR_HISTORY = 'CLEAR_HISTORY';
export const FETCH_WORD_DETAILS_REQUEST = 'FETCH_WORD_DETAILS_REQUEST';
export const FETCH_WORD_DETAILS_SUCCESS = 'FETCH_WORD_DETAILS_SUCCESS';
export const FETCH_WORD_DETAILS_FAILURE = 'FETCH_WORD_DETAILS_FAILURE';